// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateKaliUserData, CreateKaliUserErrors, CreateKaliUserResponses, DeleteModelData, DeleteModelErrors, DeleteModelResponses, DeleteTargetData, DeleteTargetErrors, DeleteTargetResponses, DownloadOllamaModelData, DownloadOllamaModelErrors, DownloadOllamaModelResponses, GetAllProjectsData, GetAllProjectsResponses, GetAllTargetsInProjectData, GetAllTargetsInProjectErrors, GetAllTargetsInProjectResponses, GetDownloadableModelsData, GetDownloadableModelsResponses, GetModelsListData, GetModelsListResponses, GetOllamaDownloadQueueDetailsData, GetOllamaDownloadQueueDetailsResponses, GetProjectSettingsData, GetProjectSettingsErrors, GetProjectSettingsResponses, KaliClientExistsData, KaliClientExistsErrors, KaliClientExistsResponses, PostProjectData, PostProjectErrors, PostProjectResponses, PostTargetData, PostTargetErrors, PostTargetResponses, UpdateProjectSettingsData, UpdateProjectSettingsErrors, UpdateProjectSettingsResponses, UpdateTargetData, UpdateTargetErrors, UpdateTargetResponses, WsTypesData, WsTypesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * All Projects
 */
export const getAllProjects = <ThrowOnError extends boolean = false>(options?: Options<GetAllProjectsData, ThrowOnError>): RequestResult<GetAllProjectsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllProjectsResponses, unknown, ThrowOnError>({ url: '/api/projects', ...options });

/**
 * Create Project
 */
export const postProject = <ThrowOnError extends boolean = false>(options: Options<PostProjectData, ThrowOnError>): RequestResult<PostProjectResponses, PostProjectErrors, ThrowOnError> => (options.client ?? client).post<PostProjectResponses, PostProjectErrors, ThrowOnError>({
    url: '/api/project',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Project Settings
 */
export const getProjectSettings = <ThrowOnError extends boolean = false>(options: Options<GetProjectSettingsData, ThrowOnError>): RequestResult<GetProjectSettingsResponses, GetProjectSettingsErrors, ThrowOnError> => (options.client ?? client).get<GetProjectSettingsResponses, GetProjectSettingsErrors, ThrowOnError>({ url: '/api/project/{project_id}/settings', ...options });

/**
 * Update Project Settings
 */
export const updateProjectSettings = <ThrowOnError extends boolean = false>(options: Options<UpdateProjectSettingsData, ThrowOnError>): RequestResult<UpdateProjectSettingsResponses, UpdateProjectSettingsErrors, ThrowOnError> => (options.client ?? client).put<UpdateProjectSettingsResponses, UpdateProjectSettingsErrors, ThrowOnError>({
    url: '/api/project/{project_id}/settings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get All Targets In Project
 */
export const getAllTargetsInProject = <ThrowOnError extends boolean = false>(options: Options<GetAllTargetsInProjectData, ThrowOnError>): RequestResult<GetAllTargetsInProjectResponses, GetAllTargetsInProjectErrors, ThrowOnError> => (options.client ?? client).get<GetAllTargetsInProjectResponses, GetAllTargetsInProjectErrors, ThrowOnError>({ url: '/api/project/{project_id}/targets', ...options });

/**
 * Create Target
 */
export const postTarget = <ThrowOnError extends boolean = false>(options: Options<PostTargetData, ThrowOnError>): RequestResult<PostTargetResponses, PostTargetErrors, ThrowOnError> => (options.client ?? client).post<PostTargetResponses, PostTargetErrors, ThrowOnError>({
    url: '/api/project/{project_id}/target',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Target
 */
export const deleteTarget = <ThrowOnError extends boolean = false>(options: Options<DeleteTargetData, ThrowOnError>): RequestResult<DeleteTargetResponses, DeleteTargetErrors, ThrowOnError> => (options.client ?? client).delete<DeleteTargetResponses, DeleteTargetErrors, ThrowOnError>({ url: '/api/target/{target_id}', ...options });

/**
 * Update Target
 */
export const updateTarget = <ThrowOnError extends boolean = false>(options: Options<UpdateTargetData, ThrowOnError>): RequestResult<UpdateTargetResponses, UpdateTargetErrors, ThrowOnError> => (options.client ?? client).put<UpdateTargetResponses, UpdateTargetErrors, ThrowOnError>({
    url: '/api/target/{target_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Kali Client
 */
export const kaliClientExists = <ThrowOnError extends boolean = false>(options: Options<KaliClientExistsData, ThrowOnError>): RequestResult<KaliClientExistsResponses, KaliClientExistsErrors, ThrowOnError> => (options.client ?? client).get<KaliClientExistsResponses, KaliClientExistsErrors, ThrowOnError>({ url: '/api/kali_client/{client_id}', ...options });

/**
 * Post Kali User
 */
export const createKaliUser = <ThrowOnError extends boolean = false>(options: Options<CreateKaliUserData, ThrowOnError>): RequestResult<CreateKaliUserResponses, CreateKaliUserErrors, ThrowOnError> => (options.client ?? client).post<CreateKaliUserResponses, CreateKaliUserErrors, ThrowOnError>({ url: '/api/project/{project_id}/kali_client', ...options });

/**
 * Get Models List
 */
export const getModelsList = <ThrowOnError extends boolean = false>(options?: Options<GetModelsListData, ThrowOnError>): RequestResult<GetModelsListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetModelsListResponses, unknown, ThrowOnError>({ url: '/api/ollama/models', ...options });

/**
 * Delete Model
 */
export const deleteModel = <ThrowOnError extends boolean = false>(options: Options<DeleteModelData, ThrowOnError>): RequestResult<DeleteModelResponses, DeleteModelErrors, ThrowOnError> => (options.client ?? client).delete<DeleteModelResponses, DeleteModelErrors, ThrowOnError>({
    url: '/api/ollama/model',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post Ollama Model
 */
export const downloadOllamaModel = <ThrowOnError extends boolean = false>(options: Options<DownloadOllamaModelData, ThrowOnError>): RequestResult<DownloadOllamaModelResponses, DownloadOllamaModelErrors, ThrowOnError> => (options.client ?? client).post<DownloadOllamaModelResponses, DownloadOllamaModelErrors, ThrowOnError>({
    url: '/api/ollama/model',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Ollama Downloadable Models
 */
export const getDownloadableModels = <ThrowOnError extends boolean = false>(options?: Options<GetDownloadableModelsData, ThrowOnError>): RequestResult<GetDownloadableModelsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetDownloadableModelsResponses, unknown, ThrowOnError>({ url: '/api/ollama/downloadable_models', ...options });

/**
 * Get Ollama Download Queue Details
 */
export const getOllamaDownloadQueueDetails = <ThrowOnError extends boolean = false>(options?: Options<GetOllamaDownloadQueueDetailsData, ThrowOnError>): RequestResult<GetOllamaDownloadQueueDetailsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetOllamaDownloadQueueDetailsResponses, unknown, ThrowOnError>({ url: '/api/ollama/download_queue', ...options });

/**
 * Ws Types Dummy
 */
export const wsTypes = <ThrowOnError extends boolean = false>(options?: Options<WsTypesData, ThrowOnError>): RequestResult<WsTypesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<WsTypesResponses, unknown, ThrowOnError>({ url: '/ws/_internal/ws-types', ...options });
