// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAllProjectsData, GetAllProjectsResponses, PutProjectData, PutProjectErrors, PutProjectResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * All Projects
 */
export const getAllProjects = <ThrowOnError extends boolean = false>(options?: Options<GetAllProjectsData, ThrowOnError>): RequestResult<GetAllProjectsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllProjectsResponses, unknown, ThrowOnError>({ url: '/api/projects', ...options });

/**
 * Create Project
 */
export const putProject = <ThrowOnError extends boolean = false>(options: Options<PutProjectData, ThrowOnError>): RequestResult<PutProjectResponses, PutProjectErrors, ThrowOnError> => (options.client ?? client).put<PutProjectResponses, PutProjectErrors, ThrowOnError>({
    url: '/api/project',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
