// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateKaliUserData, CreateKaliUserErrors, CreateKaliUserResponses, DeleteModelData, DeleteModelErrors, DeleteModelResponses, DeleteProjectData, DeleteProjectErrors, DeleteProjectResponses, DeleteTargetData, DeleteTargetErrors, DeleteTargetResponses, DeleteVulnerabilityData, DeleteVulnerabilityErrors, DeleteVulnerabilityResponses, DownloadOllamaModelData, DownloadOllamaModelErrors, DownloadOllamaModelResponses, GetAllProjectsData, GetAllProjectsResponses, GetAllTargetsInProjectData, GetAllTargetsInProjectErrors, GetAllTargetsInProjectResponses, GetAllVulnerabilitiesInProjectData, GetAllVulnerabilitiesInProjectErrors, GetAllVulnerabilitiesInProjectResponses, GetDownloadableModelsData, GetDownloadableModelsResponses, GetModelsListData, GetModelsListResponses, GetOllamaDownloadQueueDetailsData, GetOllamaDownloadQueueDetailsResponses, GetProjectAgentLogsData, GetProjectAgentLogsErrors, GetProjectAgentLogsResponses, GetProjectKaliClientData, GetProjectKaliClientErrors, GetProjectKaliClientResponses, GetProjectKaliStatusData, GetProjectKaliStatusErrors, GetProjectKaliStatusResponses, GetProjectSettingsData, GetProjectSettingsErrors, GetProjectSettingsResponses, GetTargetAgentRunData, GetTargetAgentRunErrors, GetTargetAgentRunResponses, IsProjectAgentRunningData, IsProjectAgentRunningErrors, IsProjectAgentRunningResponses, KaliClientExistsData, KaliClientExistsErrors, KaliClientExistsResponses, PauseAgentData, PauseAgentErrors, PauseAgentResponses, PostProjectData, PostProjectErrors, PostProjectResponses, PostTargetData, PostTargetErrors, PostTargetResponses, StartAgentData, StartAgentErrors, StartAgentResponses, UpdateProjectSettingsData, UpdateProjectSettingsErrors, UpdateProjectSettingsResponses, UpdateTargetData, UpdateTargetErrors, UpdateTargetResponses, UpdateVulnerabilityData, UpdateVulnerabilityErrors, UpdateVulnerabilityResponses, WsTypesData, WsTypesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * All Projects
 */
export const getAllProjects = <ThrowOnError extends boolean = false>(options?: Options<GetAllProjectsData, ThrowOnError>): RequestResult<GetAllProjectsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllProjectsResponses, unknown, ThrowOnError>({ url: '/api/projects', ...options });

/**
 * Create Project
 */
export const postProject = <ThrowOnError extends boolean = false>(options: Options<PostProjectData, ThrowOnError>): RequestResult<PostProjectResponses, PostProjectErrors, ThrowOnError> => (options.client ?? client).post<PostProjectResponses, PostProjectErrors, ThrowOnError>({
    url: '/api/project',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Project Settings
 */
export const getProjectSettings = <ThrowOnError extends boolean = false>(options: Options<GetProjectSettingsData, ThrowOnError>): RequestResult<GetProjectSettingsResponses, GetProjectSettingsErrors, ThrowOnError> => (options.client ?? client).get<GetProjectSettingsResponses, GetProjectSettingsErrors, ThrowOnError>({ url: '/api/project/{project_id}/settings', ...options });

/**
 * Update Project Settings
 */
export const updateProjectSettings = <ThrowOnError extends boolean = false>(options: Options<UpdateProjectSettingsData, ThrowOnError>): RequestResult<UpdateProjectSettingsResponses, UpdateProjectSettingsErrors, ThrowOnError> => (options.client ?? client).put<UpdateProjectSettingsResponses, UpdateProjectSettingsErrors, ThrowOnError>({
    url: '/api/project/{project_id}/settings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Project
 */
export const deleteProject = <ThrowOnError extends boolean = false>(options: Options<DeleteProjectData, ThrowOnError>): RequestResult<DeleteProjectResponses, DeleteProjectErrors, ThrowOnError> => (options.client ?? client).delete<DeleteProjectResponses, DeleteProjectErrors, ThrowOnError>({ url: '/api/project/{project_id}', ...options });

/**
 * Get All Targets In Project
 */
export const getAllTargetsInProject = <ThrowOnError extends boolean = false>(options: Options<GetAllTargetsInProjectData, ThrowOnError>): RequestResult<GetAllTargetsInProjectResponses, GetAllTargetsInProjectErrors, ThrowOnError> => (options.client ?? client).get<GetAllTargetsInProjectResponses, GetAllTargetsInProjectErrors, ThrowOnError>({ url: '/api/project/{project_id}/targets', ...options });

/**
 * Create Target
 */
export const postTarget = <ThrowOnError extends boolean = false>(options: Options<PostTargetData, ThrowOnError>): RequestResult<PostTargetResponses, PostTargetErrors, ThrowOnError> => (options.client ?? client).post<PostTargetResponses, PostTargetErrors, ThrowOnError>({
    url: '/api/project/{project_id}/target',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Target
 */
export const deleteTarget = <ThrowOnError extends boolean = false>(options: Options<DeleteTargetData, ThrowOnError>): RequestResult<DeleteTargetResponses, DeleteTargetErrors, ThrowOnError> => (options.client ?? client).delete<DeleteTargetResponses, DeleteTargetErrors, ThrowOnError>({ url: '/api/target/{target_id}', ...options });

/**
 * Update Target
 */
export const updateTarget = <ThrowOnError extends boolean = false>(options: Options<UpdateTargetData, ThrowOnError>): RequestResult<UpdateTargetResponses, UpdateTargetErrors, ThrowOnError> => (options.client ?? client).put<UpdateTargetResponses, UpdateTargetErrors, ThrowOnError>({
    url: '/api/target/{target_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Kali Client
 */
export const kaliClientExists = <ThrowOnError extends boolean = false>(options: Options<KaliClientExistsData, ThrowOnError>): RequestResult<KaliClientExistsResponses, KaliClientExistsErrors, ThrowOnError> => (options.client ?? client).get<KaliClientExistsResponses, KaliClientExistsErrors, ThrowOnError>({ url: '/api/kali_client/{client_id}', ...options });

/**
 * Get Project Kali Client
 */
export const getProjectKaliClient = <ThrowOnError extends boolean = false>(options: Options<GetProjectKaliClientData, ThrowOnError>): RequestResult<GetProjectKaliClientResponses, GetProjectKaliClientErrors, ThrowOnError> => (options.client ?? client).get<GetProjectKaliClientResponses, GetProjectKaliClientErrors, ThrowOnError>({ url: '/api/project/{project_id}/kali_client', ...options });

/**
 * Post Kali User
 */
export const createKaliUser = <ThrowOnError extends boolean = false>(options: Options<CreateKaliUserData, ThrowOnError>): RequestResult<CreateKaliUserResponses, CreateKaliUserErrors, ThrowOnError> => (options.client ?? client).post<CreateKaliUserResponses, CreateKaliUserErrors, ThrowOnError>({ url: '/api/project/{project_id}/kali_client', ...options });

/**
 * Get Project Kali Status
 */
export const getProjectKaliStatus = <ThrowOnError extends boolean = false>(options: Options<GetProjectKaliStatusData, ThrowOnError>): RequestResult<GetProjectKaliStatusResponses, GetProjectKaliStatusErrors, ThrowOnError> => (options.client ?? client).get<GetProjectKaliStatusResponses, GetProjectKaliStatusErrors, ThrowOnError>({ url: '/api/project/{project_id}/kali/status', ...options });

/**
 * Get Models List
 */
export const getModelsList = <ThrowOnError extends boolean = false>(options?: Options<GetModelsListData, ThrowOnError>): RequestResult<GetModelsListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetModelsListResponses, unknown, ThrowOnError>({ url: '/api/ollama/models', ...options });

/**
 * Delete Model
 */
export const deleteModel = <ThrowOnError extends boolean = false>(options: Options<DeleteModelData, ThrowOnError>): RequestResult<DeleteModelResponses, DeleteModelErrors, ThrowOnError> => (options.client ?? client).delete<DeleteModelResponses, DeleteModelErrors, ThrowOnError>({
    url: '/api/ollama/model',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post Ollama Model
 */
export const downloadOllamaModel = <ThrowOnError extends boolean = false>(options: Options<DownloadOllamaModelData, ThrowOnError>): RequestResult<DownloadOllamaModelResponses, DownloadOllamaModelErrors, ThrowOnError> => (options.client ?? client).post<DownloadOllamaModelResponses, DownloadOllamaModelErrors, ThrowOnError>({
    url: '/api/ollama/model',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Ollama Downloadable Models
 */
export const getDownloadableModels = <ThrowOnError extends boolean = false>(options?: Options<GetDownloadableModelsData, ThrowOnError>): RequestResult<GetDownloadableModelsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetDownloadableModelsResponses, unknown, ThrowOnError>({ url: '/api/ollama/downloadable_models', ...options });

/**
 * Get Ollama Download Queue Details
 */
export const getOllamaDownloadQueueDetails = <ThrowOnError extends boolean = false>(options?: Options<GetOllamaDownloadQueueDetailsData, ThrowOnError>): RequestResult<GetOllamaDownloadQueueDetailsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetOllamaDownloadQueueDetailsResponses, unknown, ThrowOnError>({ url: '/api/ollama/download_queue', ...options });

/**
 * Start Agent
 */
export const startAgent = <ThrowOnError extends boolean = false>(options: Options<StartAgentData, ThrowOnError>): RequestResult<StartAgentResponses, StartAgentErrors, ThrowOnError> => (options.client ?? client).post<StartAgentResponses, StartAgentErrors, ThrowOnError>({ url: '/api/project/{project_id}/target/{target_id}/agent/start', ...options });

/**
 * Pause Agent
 */
export const pauseAgent = <ThrowOnError extends boolean = false>(options: Options<PauseAgentData, ThrowOnError>): RequestResult<PauseAgentResponses, PauseAgentErrors, ThrowOnError> => (options.client ?? client).post<PauseAgentResponses, PauseAgentErrors, ThrowOnError>({ url: '/api/project/{project_id}/target/{target_id}/agent/pause', ...options });

/**
 * Get Project Agent Logs
 */
export const getProjectAgentLogs = <ThrowOnError extends boolean = false>(options: Options<GetProjectAgentLogsData, ThrowOnError>): RequestResult<GetProjectAgentLogsResponses, GetProjectAgentLogsErrors, ThrowOnError> => (options.client ?? client).get<GetProjectAgentLogsResponses, GetProjectAgentLogsErrors, ThrowOnError>({ url: '/api/project/{project_id}/agent_logs', ...options });

/**
 * Is Project Agent Running
 */
export const isProjectAgentRunning = <ThrowOnError extends boolean = false>(options: Options<IsProjectAgentRunningData, ThrowOnError>): RequestResult<IsProjectAgentRunningResponses, IsProjectAgentRunningErrors, ThrowOnError> => (options.client ?? client).get<IsProjectAgentRunningResponses, IsProjectAgentRunningErrors, ThrowOnError>({ url: '/api/project/{project_id}/agent/running', ...options });

/**
 * Get Target Agent Run
 */
export const getTargetAgentRun = <ThrowOnError extends boolean = false>(options: Options<GetTargetAgentRunData, ThrowOnError>): RequestResult<GetTargetAgentRunResponses, GetTargetAgentRunErrors, ThrowOnError> => (options.client ?? client).get<GetTargetAgentRunResponses, GetTargetAgentRunErrors, ThrowOnError>({ url: '/api/project/{project_id}/target/{target_id}/agent/run', ...options });

/**
 * Get All Vulnerabilities In Project
 */
export const getAllVulnerabilitiesInProject = <ThrowOnError extends boolean = false>(options: Options<GetAllVulnerabilitiesInProjectData, ThrowOnError>): RequestResult<GetAllVulnerabilitiesInProjectResponses, GetAllVulnerabilitiesInProjectErrors, ThrowOnError> => (options.client ?? client).get<GetAllVulnerabilitiesInProjectResponses, GetAllVulnerabilitiesInProjectErrors, ThrowOnError>({ url: '/api/project/{project_id}/vulnerabilities', ...options });

/**
 * Delete Vulnerability
 */
export const deleteVulnerability = <ThrowOnError extends boolean = false>(options: Options<DeleteVulnerabilityData, ThrowOnError>): RequestResult<DeleteVulnerabilityResponses, DeleteVulnerabilityErrors, ThrowOnError> => (options.client ?? client).delete<DeleteVulnerabilityResponses, DeleteVulnerabilityErrors, ThrowOnError>({ url: '/api/vulnerability/{vulnerability_id}', ...options });

/**
 * Update Vulnerability
 */
export const updateVulnerability = <ThrowOnError extends boolean = false>(options: Options<UpdateVulnerabilityData, ThrowOnError>): RequestResult<UpdateVulnerabilityResponses, UpdateVulnerabilityErrors, ThrowOnError> => (options.client ?? client).put<UpdateVulnerabilityResponses, UpdateVulnerabilityErrors, ThrowOnError>({
    url: '/api/vulnerability/{vulnerability_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Ws Types Dummy
 */
export const wsTypes = <ThrowOnError extends boolean = false>(options?: Options<WsTypesData, ThrowOnError>): RequestResult<WsTypesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<WsTypesResponses, unknown, ThrowOnError>({ url: '/ws/_internal/ws-types', ...options });
