// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ProjectBase
 */
export type ProjectBase = {
    /**
     * Name
     */
    name: string;
};

/**
 * Project
 */
export type ProjectResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
};

/**
 * ResponseTarget
 */
export type ResponseTarget = {
    /**
     * Name
     */
    name: string;
    /**
     * Ipv4
     */
    ipv4: string | null;
    /**
     * Ipv6
     */
    ipv6: string | null;
    /**
     * Domain
     */
    domain: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Ports
     */
    ports: Array<number> | null;
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
};

/**
 * TargetBase
 */
export type TargetBase = {
    /**
     * Name
     */
    name: string;
    /**
     * Ipv4
     */
    ipv4: string | null;
    /**
     * Ipv6
     */
    ipv6: string | null;
    /**
     * Domain
     */
    domain: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Ports
     */
    ports: Array<number> | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetAllProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type GetAllProjectsResponses = {
    /**
     * Response Getallprojects
     *
     * Successful Response
     */
    200: Array<ProjectResponse>;
};

export type GetAllProjectsResponse = GetAllProjectsResponses[keyof GetAllProjectsResponses];

export type PostProjectData = {
    body: ProjectBase;
    path?: never;
    query?: never;
    url: '/api/project';
};

export type PostProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostProjectError = PostProjectErrors[keyof PostProjectErrors];

export type PostProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type PostProjectResponse = PostProjectResponses[keyof PostProjectResponses];

export type GetAllTargetsInProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/project/{project_id}/targets';
};

export type GetAllTargetsInProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllTargetsInProjectError = GetAllTargetsInProjectErrors[keyof GetAllTargetsInProjectErrors];

export type GetAllTargetsInProjectResponses = {
    /**
     * Response Getalltargetsinproject
     *
     * Successful Response
     */
    200: Array<ResponseTarget>;
};

export type GetAllTargetsInProjectResponse = GetAllTargetsInProjectResponses[keyof GetAllTargetsInProjectResponses];

export type PostTargetData = {
    body: TargetBase;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/project/{project_id}/target';
};

export type PostTargetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostTargetError = PostTargetErrors[keyof PostTargetErrors];

export type PostTargetResponses = {
    /**
     * Successful Response
     */
    200: ResponseTarget;
};

export type PostTargetResponse = PostTargetResponses[keyof PostTargetResponses];

export type DeleteTargetData = {
    body?: never;
    path: {
        /**
         * Target Id
         */
        target_id: string;
    };
    query?: never;
    url: '/api/target/{target_id}';
};

export type DeleteTargetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTargetError = DeleteTargetErrors[keyof DeleteTargetErrors];

export type DeleteTargetResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTargetResponse = DeleteTargetResponses[keyof DeleteTargetResponses];
