// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CreatedKaliUserMessage
 */
export type CreatedKaliUserMessage = {
    /**
     * Type
     */
    type: 'CreatedKaliUserMessage';
    error?: WebSocketError | null;
    /**
     * Client Id
     */
    client_id: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InboundTraffic
 */
export type InboundTraffic = SendCommandMessage;

/**
 * KaliUser
 */
export type KaliUser = {
    /**
     * Client Id
     */
    client_id: string;
    /**
     * Pending
     */
    pending?: boolean | null;
};

/**
 * ListResponse
 */
export type ListResponse = {
    /**
     * Models
     */
    models: Array<Model>;
};

/**
 * Model
 */
export type Model = {
    /**
     * Model
     */
    model?: string | null;
    /**
     * Modified At
     */
    modified_at?: string | null;
    /**
     * Digest
     */
    digest?: string | null;
    /**
     * Size
     */
    size?: number | null;
    details?: ModelDetails | null;
};

/**
 * ModelData
 */
export type ModelData = {
    /**
     * Model Name
     */
    model_name: string;
};

/**
 * ModelDetails
 */
export type ModelDetails = {
    /**
     * Parent Model
     */
    parent_model?: string | null;
    /**
     * Format
     */
    format?: string | null;
    /**
     * Family
     */
    family?: string | null;
    /**
     * Families
     */
    families?: Array<string> | null;
    /**
     * Parameter Size
     */
    parameter_size?: string | null;
    /**
     * Quantization Level
     */
    quantization_level?: string | null;
};

/**
 * ModelPullingUpdate
 */
export type ModelPullingUpdate = {
    /**
     * Model
     */
    model: string;
    /**
     * Status
     */
    status: string;
    /**
     * Completed
     */
    completed: number;
    /**
     * Total
     */
    total: number;
    /**
     * Type
     */
    type: 'ModelPullingUpdate';
    error?: WebSocketError | null;
};

/**
 * OutboundTraffic
 */
export type OutboundTraffic = ReceiveCommandOutputMessage | CreatedKaliUserMessage | ModelPullingUpdate;

/**
 * PostRequestOllamaModel
 */
export type PostRequestOllamaModel = {
    /**
     * Model Name
     */
    model_name: string;
    /**
     * Project Id
     */
    project_id: string;
};

/**
 * ProjectBase
 */
export type ProjectBase = {
    /**
     * Name
     */
    name: string;
};

/**
 * Project
 */
export type ProjectResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
};

/**
 * ReceiveCommandOutputMessage
 */
export type ReceiveCommandOutputMessage = {
    /**
     * Type
     */
    type: 'ReceiveCommandOutputMessage';
    error?: WebSocketError | null;
    /**
     * Output
     */
    output: string;
};

/**
 * ResponseTarget
 */
export type ResponseTarget = {
    /**
     * Name
     */
    name: string;
    /**
     * Ipv4
     */
    ipv4: string | null;
    /**
     * Ipv6
     */
    ipv6: string | null;
    /**
     * Domain
     */
    domain: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Ports
     */
    ports: Array<number> | null;
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
};

/**
 * SendCommandMessage
 */
export type SendCommandMessage = {
    /**
     * Type
     */
    type: 'SendCommandMessage';
    /**
     * Command
     */
    command: string;
    /**
     * User
     */
    user: 'root' | 'momos';
};

/**
 * TargetBase
 */
export type TargetBase = {
    /**
     * Name
     */
    name: string;
    /**
     * Ipv4
     */
    ipv4: string | null;
    /**
     * Ipv6
     */
    ipv6: string | null;
    /**
     * Domain
     */
    domain: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Ports
     */
    ports: Array<number> | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WebSocketError
 */
export type WebSocketError = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string | null;
};

/**
 * WebsocketTrafficSchema
 */
export type WebsocketTrafficSchema = {
    inbound_traffic: InboundTraffic;
    outbound_traffic: OutboundTraffic;
};

export type GetAllProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type GetAllProjectsResponses = {
    /**
     * Response Getallprojects
     *
     * Successful Response
     */
    200: Array<ProjectResponse>;
};

export type GetAllProjectsResponse = GetAllProjectsResponses[keyof GetAllProjectsResponses];

export type PostProjectData = {
    body: ProjectBase;
    path?: never;
    query?: never;
    url: '/api/project';
};

export type PostProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostProjectError = PostProjectErrors[keyof PostProjectErrors];

export type PostProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type PostProjectResponse = PostProjectResponses[keyof PostProjectResponses];

export type GetAllTargetsInProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/project/{project_id}/targets';
};

export type GetAllTargetsInProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllTargetsInProjectError = GetAllTargetsInProjectErrors[keyof GetAllTargetsInProjectErrors];

export type GetAllTargetsInProjectResponses = {
    /**
     * Response Getalltargetsinproject
     *
     * Successful Response
     */
    200: Array<ResponseTarget>;
};

export type GetAllTargetsInProjectResponse = GetAllTargetsInProjectResponses[keyof GetAllTargetsInProjectResponses];

export type PostTargetData = {
    body: TargetBase;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/project/{project_id}/target';
};

export type PostTargetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostTargetError = PostTargetErrors[keyof PostTargetErrors];

export type PostTargetResponses = {
    /**
     * Successful Response
     */
    200: ResponseTarget;
};

export type PostTargetResponse = PostTargetResponses[keyof PostTargetResponses];

export type DeleteTargetData = {
    body?: never;
    path: {
        /**
         * Target Id
         */
        target_id: string;
    };
    query?: never;
    url: '/api/target/{target_id}';
};

export type DeleteTargetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTargetError = DeleteTargetErrors[keyof DeleteTargetErrors];

export type DeleteTargetResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTargetResponse = DeleteTargetResponses[keyof DeleteTargetResponses];

export type UpdateTargetData = {
    body: TargetBase;
    path: {
        /**
         * Target Id
         */
        target_id: string;
    };
    query?: never;
    url: '/api/target/{target_id}';
};

export type UpdateTargetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTargetError = UpdateTargetErrors[keyof UpdateTargetErrors];

export type UpdateTargetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type KaliClientExistsData = {
    body?: never;
    path: {
        /**
         * Client Id
         */
        client_id: string;
    };
    query?: never;
    url: '/api/kali_client/{client_id}';
};

export type KaliClientExistsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KaliClientExistsError = KaliClientExistsErrors[keyof KaliClientExistsErrors];

export type KaliClientExistsResponses = {
    /**
     * Successful Response
     */
    200: KaliUser;
};

export type KaliClientExistsResponse = KaliClientExistsResponses[keyof KaliClientExistsResponses];

export type CreateKaliUserData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/project/{project_id}/kali_client';
};

export type CreateKaliUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKaliUserError = CreateKaliUserErrors[keyof CreateKaliUserErrors];

export type CreateKaliUserResponses = {
    /**
     * Successful Response
     */
    200: KaliUser;
};

export type CreateKaliUserResponse = CreateKaliUserResponses[keyof CreateKaliUserResponses];

export type GetModelsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ollama/models';
};

export type GetModelsListResponses = {
    /**
     * Successful Response
     */
    200: ListResponse;
};

export type GetModelsListResponse = GetModelsListResponses[keyof GetModelsListResponses];

export type DeleteModelData = {
    body: ModelData;
    path?: never;
    query?: never;
    url: '/api/ollama/model';
};

export type DeleteModelErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteModelError = DeleteModelErrors[keyof DeleteModelErrors];

export type DeleteModelResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostModelData = {
    body: PostRequestOllamaModel;
    path?: never;
    query?: never;
    url: '/api/ollama/model';
};

export type PostModelErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostModelError = PostModelErrors[keyof PostModelErrors];

export type PostModelResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type WsTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ws/_internal/ws-types';
};

export type WsTypesResponses = {
    /**
     * Successful Response
     */
    200: WebsocketTrafficSchema;
};

export type WsTypesResponse = WsTypesResponses[keyof WsTypesResponses];
